kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-web-deployment
  namespace: prod-stablecog
  labels:
    app: sc-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sc-web
  template:
    metadata:
      labels:
        app: sc-web
    spec:
      containers:
        - name: sc-web
          image: replaceme
          ports:
            - containerPort: 3000
          imagePullPolicy: 'Always'
          resources:
            requests:
              cpu: '2000m'
              memory: '2000Mi'
            limits:
              cpu: '4000m'
              memory: '4000Gi'
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: sc-web-secrets
