name: 💫 CI (Stablecog Website)

on:
  push:
    branches: [master]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_amd64:
    name: 🔨 Build Docker Image (amd64)
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${{ github.sha::7 }}" >> $GITHUB_ENV

      - name: Set COMMIT_MSG
        run: echo "COMMIT_MSG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Set BRANCH_NAME
        run: |
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build amd64 image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false # Only build, don't push yet
          file: ./Dockerfile
          tags: stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64

      - name: Push amd64 image
        run: |
          docker push stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64

  build_arm64:
    name: 🔨 Build Docker Image (arm64)
    runs-on: warp-ubuntu-latest-arm64-8x
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${{ github.sha::7 }}" >> $GITHUB_ENV

      - name: Set COMMIT_MSG
        run: echo "COMMIT_MSG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Set BRANCH_NAME
        run: |
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build arm64 image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: false # Only build, don't push yet
          file: ./Dockerfile
          tags: stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64

      - name: Push arm64 image
        run: |
          docker push stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64

  push_manifest:
    name: 🏷️ Push Multi-Arch Manifest
    runs-on: ubuntu-latest
    needs:
      - build_amd64
      - build_arm64

    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }} \
            stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64 \
            stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64
          docker manifest push stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}

      - name: Tag and push 'latest'
        run: |
          docker manifest create stablecog/sc-web:latest \
            stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64 \
            stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64
          docker manifest push stablecog/sc-web:latest

  deploy:
    name: 🚀 Deploy Stablecog Website
    runs-on: warp-ubuntu-latest-x64-8x
    needs:
      - push_manifest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA, BRANCH_NAME, and COMMIT_MSG
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          COMMIT_MSG=${{ github.event.head_commit.message }}
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          else
            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)
          fi
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Deploy
        uses: ./.github/actions/k3s-deploy
        with:
          image: stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}
          embed-title: '${{ env.COMMIT_MSG }}  •  ${{ env.SHORT_SHA }}'
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          kube_config: ${{ secrets.K3S_KUBE_CONFIG }}
