name: 💫 CI (Stablecog Website)

on:
  push:
    branches: [master]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discord_notification_build_started:
    name: 📡 Discord Notification (Build Started)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA::7}`" >> $GITHUB_ENV

      - name: Put commit msg in environment
        run: echo "COMMIT_MSG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Escape commit message
        run: |
          echo "COMMIT_MSG=$(echo $COMMIT_MSG | tr -d \'\\\")" >> $GITHUB_ENV

      - name: Send Discord Webhook
        uses: ./.github/actions/discord-webhook
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-color: 16776960
          embed-title: '[sc-web] ${{ env.COMMIT_MSG }}  •  ${{ env.SHORT_SHA }}'
          embed-description: '```Build Started```'
  build_amd64:
    name: 🔨 Build Docker Image (amd64)
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set BRANCH_NAME
        run: |
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          else
            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Validate Environment Variables
        run: |
          if [ -z "${{ env.BRANCH_NAME }}" ] || [ -z "${{ env.SHORT_SHA }}" ]; then
            echo "BRANCH_NAME or SHORT_SHA is not set correctly. Exiting..."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag amd64 Image
        run: |
          docker buildx build --platform linux/amd64 -t stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64 --load .

      - name: Push amd64 Image
        run: |
          docker push stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64

  build_arm64:
    name: 🔨 Build Docker Image (arm64)
    runs-on: warp-ubuntu-latest-arm64-4x
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set BRANCH_NAME
        run: |
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          else
            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Validate Environment Variables
        run: |
          if [ -z "${{ env.BRANCH_NAME }}" ] || [ -z "${{ env.SHORT_SHA }}" ]; then
            echo "BRANCH_NAME or SHORT_SHA is not set correctly. Exiting..."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag arm64 Image
        run: |
          docker buildx build --platform linux/arm64 -t stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64 --load .

      - name: Push arm64 Image
        run: |
          docker push stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64

  push_manifest:
    name: 🏷️ Push Multi-architecture Image
    runs-on: ubuntu-latest
    needs:
      - build_amd64
      - build_arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set BRANCH_NAME
        run: |
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          else
            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Validate Environment Variables
        run: |
          if [ -z "${{ env.BRANCH_NAME }}" ] || [ -z "${{ env.SHORT_SHA }}" ]; then
            echo "BRANCH_NAME or SHORT_SHA is not set correctly. Exiting..."
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker manifest create stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }} \
            --amend stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64 \
            --amend stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64
          docker manifest push stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}

      - name: Tag and Push 'latest'
        run: |
          docker manifest create stablecog/sc-web:latest \
            --amend stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-amd64 \
            --amend stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}-arm64
          docker manifest push stablecog/sc-web:latest

  deploy:
    name: 🚀 Deploy Stablecog Website
    runs-on: warp-ubuntu-latest-x64-4x
    needs:
      - push_manifest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA, BRANCH_NAME, and COMMIT_MSG
        run: |
          SHORT_SHA=$(echo '${{ github.sha }}' | cut -c1-7)
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [ "${{ github.event_name }}" != 'pull_request' ]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          else
            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)
          fi
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Deploy
        uses: ./.github/actions/k3s-deploy
        with:
          image: stablecog/sc-web:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}
          embed-title: '${{ env.COMMIT_MSG }}  •  ${{ env.SHORT_SHA }}'
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          kube_config: ${{ secrets.K3S_KUBE_CONFIG }}
